package no.uio.taco.pukaMatControl.puka;

/*
 * frmConnectToDatabase.java
 *
 * Created on June 24, 2004, 11:01 AM
 */

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author  jaetzel
 */
public class frmConnectToDatabase extends javax.swing.JInternalFrame {
  
  /** Creates new form frmConnectToDatabase */
  public frmConnectToDatabase() {
		ArrayList jcNameList = new ArrayList();
		
		setFrameIcon(new ImageIcon(frmPreferences.getInstallPath() + "iconSmall.gif"));
    setBounds(50, 40, 400, 300);
		initComponents();
		
		//check if databases were read from the preferences file, if not, disable database stuff
		jcNameList = frmPreferences.getDBNames();
		if (jcNameList.size() == 0) { 
			cboDBName.setEnabled(false);
			txtUserName.setEnabled(false);
			txtPassword.setEnabled(false);
			rdoNoDatabase.setSelected(true);
		}
		else {
			java.util.Iterator jcIterator = jcNameList.iterator();
			while (jcIterator.hasNext()) { cboDBName.addItem((String)jcIterator.next()); }
		}
	
  }
  
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    java.awt.GridBagConstraints gridBagConstraints;

    buttonGroup1 = new javax.swing.ButtonGroup();
    lblDBName = new javax.swing.JLabel();
    cmdOK = new javax.swing.JButton();
    cboDBName = new javax.swing.JComboBox();
    lblUserName = new javax.swing.JLabel();
    txtUserName = new javax.swing.JTextField();
    lblPassword = new javax.swing.JLabel();
    txtPassword = new javax.swing.JTextField();
    lblTop1 = new javax.swing.JLabel();
    lblTop2 = new javax.swing.JLabel();
    rdoUseDatabase = new javax.swing.JRadioButton();
    rdoNoDatabase = new javax.swing.JRadioButton();
    cmdCancel = new javax.swing.JButton();

    getContentPane().setLayout(new java.awt.GridBagLayout());

    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Connect to the Database");
    lblDBName.setText("connect to this database");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    getContentPane().add(lblDBName, gridBagConstraints);

    cmdOK.setText("OK");
    cmdOK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmdOKActionPerformed(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
    gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
    getContentPane().add(cmdOK, gridBagConstraints);

    cboDBName.setPreferredSize(new java.awt.Dimension(100, 19));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
    getContentPane().add(cboDBName, gridBagConstraints);

    lblUserName.setText("username");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
    getContentPane().add(lblUserName, gridBagConstraints);

    txtUserName.setText("root");
    txtUserName.setPreferredSize(new java.awt.Dimension(100, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 0);
    getContentPane().add(txtUserName, gridBagConstraints);

    lblPassword.setText("password");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
    getContentPane().add(lblPassword, gridBagConstraints);

    txtPassword.setPreferredSize(new java.awt.Dimension(100, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 0);
    getContentPane().add(txtPassword, gridBagConstraints);

    lblTop1.setText("To change the database names on this screen use the Preferences menu.");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 3;
    getContentPane().add(lblTop1, gridBagConstraints);

    lblTop2.setText("Enter the username and password for the database, not this program.");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
    getContentPane().add(lblTop2, gridBagConstraints);

    rdoUseDatabase.setSelected(true);
    rdoUseDatabase.setText("connect to a database");
    buttonGroup1.add(rdoUseDatabase);
    rdoUseDatabase.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rdoUseDatabaseActionPerformed(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
    getContentPane().add(rdoUseDatabase, gridBagConstraints);

    rdoNoDatabase.setText("no database");
    buttonGroup1.add(rdoNoDatabase);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
    getContentPane().add(rdoNoDatabase, gridBagConstraints);

    cmdCancel.setText("Cancel");
    cmdCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmdCancelActionPerformed(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
    getContentPane().add(cmdCancel, gridBagConstraints);

    pack();
  }//GEN-END:initComponents

	private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
		//just close the form, don't change anything
		
		try { this.setClosed(true); } //close the form
		catch(java.beans.PropertyVetoException e) { e.printStackTrace(); }
	}//GEN-LAST:event_cmdCancelActionPerformed

	private void rdoUseDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoUseDatabaseActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_rdoUseDatabaseActionPerformed

  private void cmdOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOKActionPerformed
		//update the variables in frmMain
		
		if (rdoUseDatabase.isSelected()) { 
			frmMain.setDBName((String)cboDBName.getSelectedItem());
			frmMain.setDBUserID(txtUserName.getText());
			frmMain.setDBPassword(txtPassword.getText());
		}
		else { frmMain.setDBName("NONE"); }
	
		//close the frame
    try {  this.setClosed(true); }
    catch(java.beans.PropertyVetoException e) { e.printStackTrace(); }
  }//GEN-LAST:event_cmdOKActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JComboBox cboDBName;
  private javax.swing.JButton cmdCancel;
  private javax.swing.JButton cmdOK;
  private javax.swing.JLabel lblDBName;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblTop1;
  private javax.swing.JLabel lblTop2;
  private javax.swing.JLabel lblUserName;
  private javax.swing.JRadioButton rdoNoDatabase;
  private javax.swing.JRadioButton rdoUseDatabase;
  private javax.swing.JTextField txtPassword;
  private javax.swing.JTextField txtUserName;
  // End of variables declaration//GEN-END:variables
  
}
