package no.uio.taco.pukaMatControl.puka;

/*
 * frmMain.java
 *
 * Created on September 5, 2002, 10:30 AM
 */

/** desktop pane for rest of classes, just handles gui
 * @author Joset A. Etzel
 */

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import java.util.ArrayList;
import java.sql.*;

public class frmMain extends javax.swing.JFrame {
	/**
	 * desktop pane for rest of classes, just handles gui
	 */
	public frmLoadData frmLD;
	private static String strDBtoConnect = "NONE"; // default value
	private static String strDBPassword = "";
	private static String strDBUserID = "";

	/** Creates new form frmMain */
	public frmMain() {
		ArrayList jcDBNames = new ArrayList();

		initComponents();

		frmPreferences frmPreferences1 = new frmPreferences();
		frmPreferences1.ReadPreferenceFile(); // look for and read
												// preferences.txt to set paths
		jcDBNames = frmPreferences1.getDBNames();
		if (jcDBNames.isEmpty()) {
			strDBtoConnect = "NONE";
		} else {
			strDBtoConnect = (String) jcDBNames.get(0);
		}
		setIconImage(Toolkit.getDefaultToolkit().getImage(frmPreferences.getInstallPath() + "iconSmall.gif"));

		mnuConnectToDatabase.doClick(); // and show the form

		// loads the class frmLoadData and shows it in frmMain's jDesktopPane1
		// strDBtoConnect
		frmLD = new frmLoadData();
		// jDesktopPane1.add(frmLD, javax.swing.JLayeredPane.DEFAULT_LAYER);
		// frmLD.show();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		jDesktopPane1 = new javax.swing.JDesktopPane();
		jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 550));
		jMenuBar1 = new javax.swing.JMenuBar();
		mnuFile = new javax.swing.JMenu();
		mnuFileLoad = new javax.swing.JMenuItem();
		mnuFileSave = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JSeparator();
		mnuFileExit = new javax.swing.JMenuItem();
		mnuAnalyze = new javax.swing.JMenu();
		mnuRespiration = new javax.swing.JMenuItem();
		mnuAnalyzeRSA = new javax.swing.JMenuItem();
		mnuTools = new javax.swing.JMenu();
		mnuPreferences = new javax.swing.JMenuItem();
		mnuConnectToDatabase = new javax.swing.JMenuItem();

		setTitle("puka");
		setMaximizedBounds(new java.awt.Rectangle(50, 50, 1000, 1000));
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				exitForm(evt);
			}
		});

		getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

		mnuFile.setMnemonic('F');
		mnuFile.setText("File");
		mnuFileLoad.setMnemonic('L');
		mnuFileLoad.setText("Load Data");
		mnuFileLoad.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuFileLoadActionPerformed(evt);
			}
		});

		mnuFile.add(mnuFileLoad);

		mnuFileSave.setMnemonic('S');
		mnuFileSave.setText("Save Results");
		mnuFileSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuFileSaveActionPerformed(evt);
			}
		});

		mnuFile.add(mnuFileSave);

		mnuFile.add(jSeparator1);

		mnuFileExit.setMnemonic('x');
		mnuFileExit.setText("Exit");
		mnuFileExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuFileExitActionPerformed(evt);
			}
		});

		mnuFile.add(mnuFileExit);

		jMenuBar1.add(mnuFile);

		mnuAnalyze.setMnemonic('A');
		mnuAnalyze.setText("Analyze");
		mnuAnalyze.setPreferredSize(new java.awt.Dimension(60, 20));
		mnuRespiration.setMnemonic('e');
		mnuRespiration.setText("Respiration");
		mnuRespiration.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuRespirationActionPerformed(evt);
			}
		});

		mnuAnalyze.add(mnuRespiration);

		mnuAnalyzeRSA.setMnemonic('R');
		mnuAnalyzeRSA.setText("HRV & RSA");
		mnuAnalyzeRSA.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuAnalyzeRSAActionPerformed(evt);
			}
		});

		mnuAnalyze.add(mnuAnalyzeRSA);

		jMenuBar1.add(mnuAnalyze);

		mnuTools.setMnemonic('T');
		mnuTools.setText("Tools");
		mnuPreferences.setMnemonic('P');
		mnuPreferences.setText("Preferences");
		mnuPreferences.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuPreferencesActionPerformed(evt);
			}
		});

		mnuTools.add(mnuPreferences);

		mnuConnectToDatabase.setText("Connect to Database");
		mnuConnectToDatabase.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnuConnectToDatabaseActionPerformed(evt);
			}
		});

		mnuTools.add(mnuConnectToDatabase);

		jMenuBar1.add(mnuTools);

		setJMenuBar(jMenuBar1);

		pack();
	}// GEN-END:initComponents

	private void mnuConnectToDatabaseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuConnectToDatabaseActionPerformed
		// show frmConnectToDatabase

		frmConnectToDatabase frmConnectToDatabase1 = new frmConnectToDatabase();
		jDesktopPane1.add(frmConnectToDatabase1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		frmConnectToDatabase1.show();
	}// GEN-LAST:event_mnuConnectToDatabaseActionPerformed

	private void mnuRespirationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuRespirationActionPerformed
		// loads and shows frmRespiration
		frmRespiration frmRespiration1 = new frmRespiration();
		jDesktopPane1.add(frmRespiration1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		frmRespiration1.setFrameIcon(new ImageIcon(frmPreferences.getInstallPath() + "iconSmall.gif"));
		frmRespiration1.show();
	}// GEN-LAST:event_mnuRespirationActionPerformed

	private void mnuPreferencesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuPreferencesActionPerformed
		// loads the class frmPreferences and shows it in frmMain's
		// jDesktopPane1
		frmPreferences frmPreferences1 = new frmPreferences();
		jDesktopPane1.add(frmPreferences1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		frmPreferences1.setFrameIcon(new ImageIcon(frmPreferences.getInstallPath() + "iconSmall.gif"));
		frmPreferences1.show();
	}// GEN-LAST:event_mnuPreferencesActionPerformed

	private void mnuFileSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuFileSaveActionPerformed
		// loads the class frmSaveData and shows it in frmMain's jDesktopPane1
		frmSaveData frmSaveData1 = new frmSaveData();
		jDesktopPane1.add(frmSaveData1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		frmSaveData1.setFrameIcon(new ImageIcon(frmPreferences.getInstallPath() + "iconSmall.gif"));
		frmSaveData1.show();
	}// GEN-LAST:event_mnuFileSaveActionPerformed

	private void mnuAnalyzeRSAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuAnalyzeRSAActionPerformed
		// loads the class frmRSA and shows it in frmMain's jDesktopPane1
		frmRSA frmRSA1 = new frmRSA();
		jDesktopPane1.add(frmRSA1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		frmRSA1.setBounds(60, 30, 600, 450);
		frmRSA1.setFrameIcon(new ImageIcon(frmPreferences.getInstallPath() + "iconSmall.gif"));
		frmRSA1.show();
	}// GEN-LAST:event_mnuAnalyzeRSAActionPerformed

	private void mnuFileLoadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuFileLoadActionPerformed
		// loads the class frmLoadData and shows it in frmMain's jDesktopPane1

		jDesktopPane1.add(frmLD, javax.swing.JLayeredPane.DEFAULT_LAYER);
		frmLD.FillBoxes(); // refresh lists of databases, clips on the screen
		frmLD.show();
	}// GEN-LAST:event_mnuFileLoadActionPerformed

	private void mnuFileExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuFileExitActionPerformed
		// close down the matlab connection and session
		frmLoadData.engMatLab.engClose();
		frmLoadData.engMatLab.kill();
		System.exit(0); // close everything else
	}// GEN-LAST:event_mnuFileExitActionPerformed

	/** Exit the Application */
	private void exitForm(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_exitForm
		// close down the matlab connection and session
		frmLoadData.engMatLab.engClose();
		frmLoadData.engMatLab.kill();
		System.exit(0); // close everything else
	}// GEN-LAST:event_exitForm

	/**
	 * handles GUI
	 * 
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (Exception e) {
			System.out.println("Couldn't use the native look and feel ");
			e.printStackTrace();
		}

		new frmMain().show();
	}

	public static Connection getDatabaseConnection() {
		// return a Connection to the database named in strDBtoConnect

		try {
			Class.forName("org.gjt.mm.mysql.Driver");
			Connection conData = DriverManager.getConnection("jdbc:mysql://localhost/" + strDBtoConnect, strDBUserID,
					strDBPassword);
			return conData;
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}

	// if strDBName = "NONE" then no database being used
	public static void setDBName(String strDBName) {
		strDBtoConnect = strDBName;
	}

	public static String getDBName() {
		return strDBtoConnect;
	}

	public static void setDBUserID(String strDBUserID1) {
		strDBUserID = strDBUserID1;
	}

	public static void setDBPassword(String strDBPassword1) {
		strDBPassword = strDBPassword1;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JDesktopPane jDesktopPane1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JMenu mnuAnalyze;
	private javax.swing.JMenuItem mnuAnalyzeRSA;
	private javax.swing.JMenuItem mnuConnectToDatabase;
	private javax.swing.JMenu mnuFile;
	private javax.swing.JMenuItem mnuFileExit;
	private javax.swing.JMenuItem mnuFileLoad;
	private javax.swing.JMenuItem mnuFileSave;
	private javax.swing.JMenuItem mnuPreferences;
	private javax.swing.JMenuItem mnuRespiration;
	private javax.swing.JMenu mnuTools;
	// End of variables declaration//GEN-END:variables

}
